spring:
  application:
    name: demoseguranca
debug: true
server:
  port: 3010
okta:
  oauth2:
    # Replace with the domain of your Auth0 tenant.
    issuer: https://dev-nknjwcnj.us.auth0.com/
    # Replace with the API Identifier for your Auth0 API.
    audience: https://engsoft2.com/alomundo
