server:
    port: 8765

spring:
    application:
        name: api-gateway
    cloud:
        gateway.server.webflux:
            discovery:
                locator:
                  enabled: true
                  lower-case-service-id: true
            routes:
                - id: currency-conversion
                  uri: lb://currency-conversion
                  predicates:
                    - Path=/convert/**
                  filters:
                    - name: CircuitBreaker
                      args:
                        name: currencyConversionCircuitBreaker
                        fallbackUri: forward:/fallback/currency-conversion
                    - RewritePath=/convert/?(?<resto>.*), /currency-conversion-feign/$\{resto}

management:
    endpoint:
        health:
            show-details: always
        gateway:
            access: read-only
        circuitbreakers:
            enabled: true
    endpoints:
        web:
            exposure:
                include: "*"

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka

resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        sliding-window-type: count-based
        sliding-window-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
