server:
    port: 8765

spring:
    application:
        name: api-gateway
    cloud:
        gateway.server.webflux:
            routes:
                - id: currency-conversion
                  uri: lb://currency-conversion
                  predicates:
                    - Path=/convert/**
                  filters:
                    - RewritePath=/convert/?(?<resto>.*), /currency-conversion-feign/$\{resto}      

management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: "*"

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka

logging:
    level:
        org.springframework.cloud.gateway: TRACE
